# Generated by Django 5.2.14 on 2026-05-26 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null para eventos a nivel plataforma (L9 admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='Quien ejecuto la accion. Null si fue el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='audit_audit_tenant__1d7666_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx')],
            },
        ),
    ]
