# Generated by Django 5.2.14 on 2026-05-26 06:54

import apps.accounts.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Nombre visible del nivel (ej. "Operador", "Supervisor").', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_reserved', models.BooleanField(default=False, help_text='Si True, este nivel esta oculto del selector al crear/editar usuarios.')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Correo electronico. Usado como identificador para login.', max_length=254, unique=True)),
                ('username', models.CharField(blank=True, help_text='Alias opcional, lowercase. Tambien acepta como identificador.', max_length=64, null=True, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name_paterno', models.CharField(max_length=64)),
                ('last_name_materno', models.CharField(blank=True, max_length=64)),
                ('level', models.IntegerField(default=0, help_text='Nivel jerarquico 0-9.')),
                ('preferred_language', models.CharField(choices=[('es', 'Espanol'), ('en', 'English')], default='es', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Si puede ingresar al Django admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant al que pertenece. NULL para L8 (agencia) y L9 (global).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['email'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PermissionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('permission_code', models.CharField(max_length=64)),
                ('allowed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permiso de nivel',
                'verbose_name_plural': 'Matriz de permisos',
                'ordering': ['level', 'permission_code'],
                'unique_together': {('level', 'permission_code')},
            },
        ),
        migrations.CreateModel(
            name='AgencyTenantAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='L9 que otorgo el acceso (auditoria).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_users', to='tenants.tenant')),
                ('user', models.ForeignKey(help_text='Usuario L8 al que se le otorga acceso.', on_delete=django.db.models.deletion.CASCADE, related_name='agency_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso de agencia a tenant',
                'verbose_name_plural': 'Accesos de agencia a tenants',
                'ordering': ['user', 'tenant'],
                'unique_together': {('user', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(max_length=64)),
                ('allowed', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Override de permiso de usuario',
                'verbose_name_plural': 'Overrides de permisos de usuario',
                'ordering': ['user', 'permission_code'],
                'unique_together': {('user', 'permission_code')},
            },
        ),
    ]
