# Generated by Django 5.2.14 on 2026-06-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_levels_and_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador URL-friendly de la agencia.', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Nombre visible.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Agencia a la que pertenece. Solo aplica a L8.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='accounts.agency'),
        ),
        migrations.CreateModel(
            name='AgencyLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('vencida', 'Vencida')], default='activa', max_length=16)),
                ('type', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='standard', max_length=16)),
                ('valid_until', models.DateField(blank=True, help_text='Fecha de expiracion. Vacio = sin expiracion.', null=True)),
                ('max_users', models.PositiveIntegerField(default=50, help_text='Limite de cuentas activas que permite la licencia.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='accounts.agency')),
            ],
            options={
                'verbose_name': 'Licencia de agencia',
                'verbose_name_plural': 'Licencias de agencia',
            },
        ),
    ]
