# Generated by Django 5.2.14 on 2026-06-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_system_tenant_and_admins'),
        ('tenants', '0003_tenant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Agencia (Tenant type=agency) a la que pertenece. Solo aplica a L8.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='tenants.tenant'),
        ),
        migrations.RemoveField(
            model_name='agencylicense',
            name='agency',
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='AgencyLicense',
        ),
    ]
