# Generated by Django 5.2.14 on 2026-06-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_agencytenantaccess_por_agencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('es', 'Espanol'), ('en', 'English'), ('ko', 'Korean')], default='es', max_length=4),
        ),
    ]
