# Generated by Django 5.2.14 on 2026-05-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador URL-friendly. Usado para subdominios y rutas.', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Nombre visible del tenant.', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Si esta inactivo, sus usuarios no pueden iniciar sesion.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
    ]
