# Generated by Django 5.2.14 on 2026-06-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('vencida', 'Vencida')], default='activa', max_length=16)),
                ('type', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='standard', max_length=16)),
                ('valid_until', models.DateField(blank=True, help_text='Fecha de expiracion. Vacio = sin expiracion.', null=True)),
                ('max_users', models.PositiveIntegerField(default=50, help_text='Limite de cuentas activas que permite la licencia.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Licencia de tenant',
                'verbose_name_plural': 'Licencias de tenant',
            },
        ),
    ]
