# Generated by Django 5.2.14 on 2026-06-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantlicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('system', 'System Company'), ('agency', 'Agencia'), ('cliente', 'Cliente')], default='cliente', help_text='Clasificacion del tenant: sistema, agencia o cliente.', max_length=16),
        ),
    ]
