# Generated by Django 5.2.14 on 2026-05-26 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBrand',
            fields=[
                ('marca', models.CharField(default='', max_length=64)),
                ('alcance', models.CharField(default='', max_length=64)),
                ('logo_login', models.TextField(blank=True, default='')),
                ('logo_sidebar', models.TextField(blank=True, default='')),
                ('logo_login_filename', models.CharField(blank=True, default='', max_length=128)),
                ('logo_sidebar_filename', models.CharField(blank=True, default='', max_length=128)),
                ('paleta_actual', models.JSONField(default=dict)),
                ('paletas_memoria', models.JSONField(default=list)),
                ('carrusel_fotos', models.JSONField(default=list)),
                ('carrusel_segundos', models.FloatField(default=4.5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Global Brand (LogiQ)',
                'verbose_name_plural': 'Global Brand (LogiQ)',
            },
        ),
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='', max_length=64)),
                ('alcance', models.CharField(default='', max_length=64)),
                ('logo_login', models.TextField(blank=True, default='')),
                ('logo_sidebar', models.TextField(blank=True, default='')),
                ('logo_login_filename', models.CharField(blank=True, default='', max_length=128)),
                ('logo_sidebar_filename', models.CharField(blank=True, default='', max_length=128)),
                ('paleta_actual', models.JSONField(default=dict)),
                ('paletas_memoria', models.JSONField(default=list)),
                ('carrusel_fotos', models.JSONField(default=list)),
                ('carrusel_segundos', models.FloatField(default=4.5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Brand Settings',
                'verbose_name_plural': 'Brand Settings',
            },
        ),
    ]
